name: Build JAX container

on:
  workflow_call:
    inputs:
      BASE_IMAGE:
        type: string
        description: 'Base docker image that provides CUDA and Python:'
        required: false
        default: ghcr.io/nvidia/jax-toolbox:base
      NIGHTLY:
        type: boolean
        description: 'Is this a nightly build?'
        required: false
        default: false

env:
  TARGET: jax
  UPLD_IMAGE: ghcr.io/nvidia/jax
  REPO_JAX: https://github.com/google/jax.git
  REPO_XLA: https://github.com/openxla/xla.git
  REF_JAX: ""
  REF_XLA: ""

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  build:
    runs-on: [self-hosted, builder]
    steps:
      - name: Print environment variables
        run: env

      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
        if: ${{github.ref != 'refs/heads/main'}}

      - name: Set build date
        shell: bash -x -e {0}
        run: |
          BUILD_DATE=$(TZ='US/Los_Angeles' date '+%Y-%m-%d')
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.UPLD_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=sha
            type=edge,branch=main
            type=raw,value=nightly-${{ env.BUILD_DATE }},enable=${{ inputs.NIGHTLY }},priority=900
            type=raw,value=latest,enable=${{ inputs.NIGHTLY }},priority=1000
            # type=schedule,suffix=-${{ env.BUILD_DATE }}
            # type=raw,value=latest,enable=${{ github.event_name == 'schedule' }},priority=1000
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels:
            org.opencontainers.image.created=${{ env.BUILD_DATE }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          file: .github/container/Dockerfile.jax
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |          
            BASE_IMAGE=${{ inputs.BASE_IMAGE }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            REPO_JAX=${{ env.REPO_JAX }}
            REPO_XLA=${{ env.REPO_XLA }}
            REF_JAX=${{ env.REF_JAX }}
            REF_XLA=${{ env.REF_XLA }}

      - name: Generate outputs and artifacts
        shell: bash -x -e {0}
        run: |
          echo "${{ steps.meta.outputs.tags }}" > image-tags-${{ env.TARGET }}.txt

      - name: Upload image tags as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-tags-${{ env.TARGET }}
          path: image-tags-${{ env.TARGET }}.txt