name: ~build CUDA+Python base container

on:
  workflow_call:
    inputs:
      UPDATE_LATEST:
        type: boolean
        description: Update the 'latest' images?
        default: false
        required: false

env:
  TARGET: base
  BASE_IMAGE: nvidia/cuda:12.1.0-devel-ubuntu22.04
  UPLD_IMAGE: ghcr.io/nvidia/jax-toolbox

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container
  
jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
        if: ${{github.ref != 'refs/heads/main'}}

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.UPLD_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=base,enable=${{ inputs.UPDATE_LATEST }},priority=1000
            type=raw,value=base-{{sha}},priority=100

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          file: .github/container/Dockerfile.base
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}

      - name: Generate outputs and artifacts
        shell: bash -x -e {0}
        run: |
          echo "${{ steps.meta.outputs.tags }}" > image-tags-${{ env.TARGET }}.txt

      - name: Upload image tags as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: image-tags-${{ env.TARGET }}
          path: image-tags-${{ env.TARGET }}.txt