name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH known hosts
        id: ssh-known-hosts
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/known_hosts << EOF
          ${{ vars.SSH_KNOWN_HOSTS }}
          EOF
          chmod 600 ~/.ssh/known_hosts
          echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT

      - name: Setup SSH config
        id: ssh-config
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/config << EOF
          ${{ vars.SSH_CONFIG }}
          EOF
          chmod 600 ~/.ssh/config

      - name: Create dated folder and generate TensorBoard query URL
        id: mkdir
        shell: bash -x -e {0}
        run: |
          FOLDER="9999-99-99/PAX"
          # copy folder
          ssh -T tensorboard rsync -av /tensorboard-logs/5072845957/ /tensorboard-logs/${FOLDER}
          # generate query URL
          (
          cat << EOF

          ## PAX MGMN nightly training: ${{ needs.metadata.outputs.BUILD_DATE }}

          [view metrics](http://${{ vars.HOSTNAME_TENSORBOARD }}:6006/#scalars&regexInput=$(jq -nr --arg url "${FOLDER}" '$url|@uri')&_smoothingWeight=0&tagFilter=seqs_per)

          EOF
          ) | tee $GITHUB_STEP_SUMMARY
