name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    uses: ./.github/workflows/_build_jax.yaml
    with:
      BUILD_DATE: 2023-05-22
      BASE_IMAGE: ghcr.io/nvidia/jax-toolbox:base
      REPO_JAX: 'https://github.com/google/jax.git'
      REF_JAX: 'main'
      REPO_XLA: 'ssh://git@nvjax-repo-staging.duckdns.org:20527/openxla/xla.git'
      REF_XLA: '8376895'
    secrets: inherit

    # runs-on: [self-hosted, small-builder]
    # steps:
    #   - name: Setup SSH agent
    #     uses: webfactory/ssh-agent@v0.8.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #   - name: Setup SSH known hosts
    #     id: ssh-known-hosts
    #     run: |
    #       mkdir -p ~/.ssh
    #       cat >> ~/.ssh/known_hosts << EOF
    #       ${{ vars.SSH_KNOWN_HOSTS }}
    #       EOF
    #       chmod 600 ~/.ssh/known_hosts
    #       echo "FILE=$(realpath ~/.ssh/known_hosts)" >> $GITHUB_OUTPUT

    #   - name: Test
    #     run: |
    #       git clone "ssh://git@nvjax-repo-staging.duckdns.org:20527/openxla/xla.git"

    #   - name: Generate dockerfile
    #     run: |
    #       cat > Dockerfile << EOF
    #       FROM ubuntu:22.04
    #       RUN apt-get update && apt-get install -y git openssh-client
    #       RUN --mount=type=ssh --mount=type=secret,id=SSH_KNOWN_HOSTS,target=/root/.ssh/known_hosts git clone ssh://git@nvjax-repo-staging.duckdns.org:20527/openxla/xla.git
    #       EOF

    #   - name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2
    #     with:
    #       driver-opts: |
    #         image=moby/buildkit:v0.10.6

    #   - name: Build docker images
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: .
    #       push: false
    #       file: Dockerfile
    #       tags: test:latest
    #       ssh: default
    #       secret-files: |
    #         "SSH_KNOWN_HOSTS=${{ steps.ssh-known-hosts.outputs.FILE }}"
