name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/known_hosts << EOF
          ${{ vars.SSH_KNOWN_HOSTS }}
          EOF
          chmod 600 ~/.ssh/known_hosts
          cp ~/.ssh/known_hosts /tmp/known_hosts

      - name: Generate dockerfile
        run: |
          cat > Dockerfile << EOF
          FROM ubuntu:22.04
          RUN apt-get update && apt-get install -y git openssh-client
          RUN --mount=type=ssh --mount=type=secret,id=KNOWN_HOSTS,target=/root/.ssh/known_hosts git clone ssh://git@nvjax-repo-staging.duckdns.org:20527/openxla/xla.git
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          file: Dockerfile
          tags: test:latest
          ssh: default
          secret-files: |
            "KNOWN_HOSTS=/tmp/known_hosts"
