name: "~Sandbox"

on:
  workflow_dispatch:
    inputs:
      BUILD_BASE:
        description: 'Build new base image or otherwise use ghcr.io/nvidia/jax-toolbox:base'
        type: boolean
        required: true
        default: true
      REPO_JAX:
        description: 'JAX repository'
        type: string
        required: true
        default: 'https://github.com/google/jax.git'
      REF_JAX:
        description: 'JAX branch, tag, or commit'
        type: string
        required: true
        default: 'main'
      REPO_XLA:
        description: 'XLA repository'
        type: string
        required: true
        default: 'https://github.com/openxla/xla.git'
      REF_XLA:
        description: 'XLA branch, tag, or commit'
        type: string
        required: true
        default: 'main'
      REPO_TE:
        description: 'Transformer Engine (TE) repository'
        type: string
        required: true
        default: 'https://github.com/NVIDIA/TransformerEngine.git'
      REF_TE:
        description: 'TE branch, tag, or commit'
        type: string
        required: true
        default: 'main'

jobs:

  metadata:
    runs-on: ubuntu-22.04
    outputs:
      BUILD_DATE: ${{ steps.date.outputs.BUILD_DATE }}
    steps:
      - name: Set metadata
        id: date
        shell: bash -x -e {0}
        run: |
          BUILD_DATE=$(TZ='US/Los_Angeles' date '+%Y-%m-%d')
          echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_OUTPUT

  build-base:
    needs: metadata
    uses: ./.github/workflows/_build_base.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
    secrets: inherit

  build-jax:
    needs: [metadata, build-base]
    uses: ./.github/workflows/_build_jax.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
      BASE_IMAGE: ${{ needs.build-base.outputs.DOCKER_TAGS }}
      REPO_JAX: ${{ inputs.REPO_JAX }}
      REF_JAX: ${{ inputs.REF_JAX }}
      REPO_XLA: ${{ inputs.REPO_XLA }}
      REF_XLA: ${{ inputs.REF_XLA }}
    secrets: inherit

  build-te:
    needs: [metadata, build-jax]
    uses: ./.github/workflows/_build_te.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
      BASE_IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAGS }}
    secrets: inherit

  build-t5x:
    needs: [metadata, build-jax]
    uses: ./.github/workflows/_build_t5x.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
      BASE_IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAGS }}
    secrets: inherit

  build-pax:
    needs: [metadata, build-jax]
    uses: ./.github/workflows/_build_pax.yaml
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
      BASE_IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAGS }}
    secrets: inherit

  build-rosetta:
    uses: ./.github/workflows/_build_rosetta.yaml
    needs: [metadata, build-t5x]
    with:
      BUILD_DATE: ${{ needs.metadata.outputs.BUILD_DATE }}
      BASE_IMAGE: ${{ needs.build-t5x.outputs.DOCKER_TAGS }}
    secrets: inherit

  test-jax:
    needs: build-jax
    uses: ./.github/workflows/_test_jax.yaml
    with:
      JAX_IMAGE: ${{ needs.build-jax.outputs.DOCKER_TAGS }}
    secrets: inherit

