name: "~Sandbox"

on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH known hosts
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/known_hosts << EOF
          ${{ vars.SSH_KNOWN_HOSTS }}
          EOF
          chmod 600 ~/.ssh/known_hosts

      - name: Clone repo
        run: |
          cat > Dockerfile << EOF
          FROM ubuntu:22.04
          RUN apt-get update && apt-get install -y git openssh-client
          RUN --mount=type=ssh git clone ssh://git@nvjax-repo-staging.duckdns.org:20527/openxla/xla.git
          EOF

          docker build --ssh default .
