name: ~Sandbox

on:
  workflow_dispatch:


jobs:

  # test-t5x:
  #   uses: ./.github/workflows/_test_t5x.yaml
  #   with:
  #     T5X_IMAGE: ghcr.io/nvidia/jax-toolbox-internal:4985776849-t5x
  #   secrets: inherit

  test-pax:
    uses: ./.github/workflows/_test_pax.yaml
    with:
      PAX_IMAGE: ghcr.io/nvidia/jax-toolbox-internal:4985776849-pax
    secrets: inherit
