name: ~test T5X

on:
  push:
  #   branches: [ "main" ] 
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '30 3 * * *'  # runs daily at 03:30 AM
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  t5x-scaling:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run SLURM jobs
        shell: bash -x -e {0}
        run: |
          ssh opc@168.138.192.147 << EOF
          date
          hostname
          sinfo
          srun --container-image=ghcr.io#nvidia/t5x:nightly-2023-04-07 --container-entrypoint test-t5x.sh --dtype bfloat16 --batch-per-gpu 16 --gpus 0,1,2,3,4,5,6,7 --epochs 7 --steps-per-epoch 100
          EOF