name: ~test T5X

on:
  #   branches: [ "main" ] 
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '30 3 * * *'  # runs daily at 03:30 AM
  ## allow manual run from the Actions tab
  workflow_call:

env:
  OCI_CLUSTER_BASTION: "opc@168.138.192.147"
  OCI_TENSORBOARD_HOST: "ubuntu@165.1.79.135"
  OCI_HOSTKEY_CLUSTER_BASTION: "168.138.192.147 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3Yj+KsRk2xL7TotfGCKiEqb03nbCTgnnDFni+4hrI9QmB9+vjHtLyLCCHDN/ndxn1ZaViMT7t+ItUVHqussnWzQg2geRlHNvMOe/2EZlCnPsp6UNlxEa6mqCZm6ARE3VQDeUFHdyG8gmy0YKshZ2s2RT6kYqo+sICOx3QLG+6ANRz+CEC/+/4FXkwW+L01BaRV+/R+WY3ompVcH7cmoo+CdWN1q7ipDtt6QNX1TvtRIz+qVt3gspQ75CkU40IZu/mjHtVlXXwog3OmSuZt0f4uV6AIRR2bfr7exj+BQKKyctJpfHIYAQRWayxGaQF3n+KOm3sR8zGhw0mJBhgSXN9"
  OCI_HOSTKEY_TENSORBOARD_HOST: "165.1.79.135 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+/i0SQXfIUF/GVFFw4XbjPObOuI5Xe7ZYS8fxYtQGXVBnaGs+2qYpmNS2GNoMhAc/w6+uP0gNJcVj0TXNWtSJgXgagO6zVqD4xGSqNOU82PsqRiJvVzjA4nTcGrBdIzh6sLwgkjuGKKjF5XhCJ6BQwPH/GLS9b16eewi3Ppmxp1SKca2sXIUPLrCOpZ4RY/hiQm9vTUfmOWuijxQcbOGWtc6ghV1IJpyCZGtvakhr/nR1LFQmDdbJ7MtKyqmoBbeiEQmlht2a7FGVQY8KTZsVSpYUUHT2zwGLBqogRlaxbv3ANavklG06ZpQJtpf300nr6Ix1UpAedhVpuJVGVJR9kyGZHrll60tjTMzy5Kq3RmxjmF9b524Ig8gMmwIi1G+sU5+OUSzVNGzeuvAhSOwKbFLFq9n8nPdBYGh2MDSm4aIv3Zl/YmyM4Ts2OdKF/BWyqUaGtgz38zUWEbZ2QvnebiTGcBkjBC4b8yMCjTubIFanjUNOFWz4E6GWW5enh5c="

jobs:

  t5x-scaling:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        shell: bash -x -e {0}
        run: |
          echo ${{ env.OCI_HOSTKEY_CLUSTER_BASTION }} >> ~/.ssh/known_hosts
          echo ${{ env.OCI_HOSTKEY_TENSORBOARD_HOST }} >> ~/.ssh/known_hosts

      - name: Run SLURM jobs
        shell: bash -x -e {0}
        run: |
          NGPU=8
          NNODE=1
          DATE=$(date "+%Y-%m-%d")
          OUTPUT_HOST="${HOME}/${DATE}-${NGPU}G${NNODE}N"
          OUTPUT_CONTAINER="/${DATE}-${NGPU}G${NNODE}N"
          ssh -o "ServerAliveInterval=10" ${{ env.OCI_CLUSTER_BASTION }} |& tee t5x.log  << EOF
          date
          hostname
          sinfo
          salloc -N 1 -t 4:00:00 --gpus-per-node=8
          mkdir -p ${OUTPUT_HOST}
          srun \
            --container-name=t5x \
            --container-image=ghcr.io#nvidia/t5x:latest \
            --container-mounts=${OUTPUT_HOST}:${OUTPUT_CONTAINER}
            --container-entrypoint \
            test-t5x.sh \
              --output ${OUTPUT_CONTAINER} \
              --dtype bfloat16 \
              --batch-per-gpu 16 \
              --gpus 0,1,2,3,4,5,6,7 \
              --epochs 7 \
              --steps-per-epoch 100
          scp -r ${OUTPUT_HOST} ${{ env.OCI_TENSORBOARD_HOST }}:/tensorboard-logs
          EOF

      - name: Postprocessing
        shell: bash -x -e {0}
        run: |
          true