name: ~test TransformerEngine

on:
  # Called from another workflow
  workflow_call:
    inputs:
      JAX_TE_IMAGE:
        type: string
        description: 'JAX-TE image build by NVIDIA/JAX-Toolbox'
        required: true
        default: 'ghcr.io/nvidia/jax-te:latest'

jobs:
  te-unit-tests:
    runs-on: [self-hosted, compute, V100]
    steps:
      - name: Print environment variables
        run: env

      - name: Print GPU information
        run: nvidia-smi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull JAX-TE image
        shell: bash -x -e {0}
        run: |
          docker pull ${{ inputs.JAX_TE_IMAGE }}
          docker tag ${{ inputs.JAX_TE_IMAGE }} jax-te:target

      - name: Run JAX-TE unit tests with docker
        shell: docker run --gpus all -v {0}:/cmd.sh -v /log:/log jax-te:target bash -e -x /cmd.sh
        run: |
          pip install pytest pytest-reportlog cuda-python
          pytest --report-log=/log/report.jsonl /opt/transformer-engine/tests/jax

      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: /log/report.jsonl