name: ~test TransformerEngine

on:
  # Called from another workflow
  workflow_call:
    inputs:
      JAX_TE_IMAGE:
        type: string
        description: 'JAX-TE image build by NVIDIA/JAX-Toolbox'
        required: true
        default: 'ghcr.io/nvidia/jax-te:latest'

jobs:
  te-unit-tests:
    runs-on: [self-hosted, compute, V100]
    steps:
      - name: Print environment variables
        run: env

      - name: Print GPU information
        run: nvidia-smi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull JAX-TE image
        shell: bash -x -e {0}
        run: |
          docker pull ${{ inputs.JAX_TE_IMAGE }}

      - name: Run JAX-TE unit tests w/ docker
        shell: docker run -v /tmp/pytest-log:/tmp/pytest-log --gpus all ${{ inputs.JAX_TE_IMAGE }} bash -x {0}
        run: |
          pip install pytest pytest-reportlog cuda-python
          pytest --report-log=/tmp/pytest-log/report.jsonl /opt/transformer-engine/tests/jax

      - name: Upload test json logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: /tmp/pytest-log/report.jsonl

