name: ~test JAX, unit

on:
  workflow_dispatch:
    inputs:
      IMAGE_JAX:
        type: string
        description: 'JAX image built by NVIDIA/JAX-Toolbox'
        required: true
        default: 'ghcr.io/nvidia/jax:latest'

jobs:

  unit-test:
    runs-on: [self-hosted, compute, V100]
    steps:
      - name: Print environment variables
        run: env

      - name: Print GPU information
        run: nvidia-smi  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull JAX image
        shell: bash -x -e {0}
        run: |
          docker pull ${{ inputs.IMAGE_JAX }}

      - name: Backend-independent tests
        shell: bash -x -e {0}
        run: |
          docker run --gpus all ${{ inputs.IMAGE_JAX }} test-jax.sh -b backend-independent

      - name: GPU-specific tests
        shell: bash -x -e {0}
        run: |
          docker run --gpus all ${{ inputs.IMAGE_JAX }} test-jax.sh -b gpu