name: WIP T5X performance benchmark

on:
  workflow_dispatch:
    inputs:
      T5X_IMAGE_TAG:
        type: string
        description: T5X container
        default: latest
        required: true

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  t5x:
    uses: ./.github/workflows/_test_t5x.yaml
    with:
      T5X_IMAGE_TAG: ${{ inputs.T5X_IMAGE_TAG }}
    secrets: inherit