name: Build JAX container

on:
  push:
  #   branches: [ "main" ] 
  pull_request:
  #   branches: [ "main" ]
  
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          CONTAINER_REPOSITORY=`echo ${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          RUN_NUMBER=`printf "%08d" $GITHUB_RUN_NUMBER`
          DATE=`date +%Y-%m-%d`
          IMAGE_BASE="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}:base"
          IMAGE_JAX="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}:jax"
          IMAGE_JAX_PIPELINE="${IMAGE_JAX}-${RUN_NUMBER}"
          IMAGE_JAX_DATED="${IMAGE_JAX}-${DATE}"
          echo "IMAGE_JAX=${IMAGE_JAX}" >> $GITHUB_ENV
          echo "IMAGE_JAX_PIPELINE=${IMAGE_JAX_PIPELINE}" >> $GITHUB_ENV
          echo "IMAGE_JAX_DATED=${IMAGE_JAX_DATED}" >> $GITHUB_ENV

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          tags: ${{ env.IMAGE_JAX }},${{ env.IMAGE_JAX_PIPELINE }},${{ env.IMAGE_JAX_DATED }}
          file: .github/container/Dockerfile.jax
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_BASE }}

  jax-unit-tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Print host information
        run: |
          hostname
          date
          nvcc --version
          nvidia-smi -L
          nvidia-smi

      - name: Print environment variables
        run: |
          set -x
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          RUN_NUMBER=`printf "%08d" $GITHUB_RUN_NUMBER`
          CONTAINER_REPO=`echo ${CONTAINER_REGISTRY}/${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE="${CONTAINER_REPO}:${RUN_NUMBER}"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        run: |
          docker run --runtime=nvidia --gpus all ${{ env.IMAGE }} test-jax.sh -b backend-independent
          docker run --runtime=nvidia --gpus all ${{ env.IMAGE }} test-jax.sh -b gpu
