name: CI

on:
  push:
  #   branches: [ "main" ] 
  pull_request:
  #   branches: [ "main" ]
  
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  large-runner-test:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: List CPUs
        run: |
          cat /proc/cpuinfo

  gpu-runner-test:
    runs-on: self-hosted
    steps:
      - name: List GPUs
        run: |
          hostname
          date
          nvcc --version
          nvidia-smi -L
          nvidia-smi

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container/
          push: true
          tags: ghcr.io/nvidia/jax-toolbox:latest
          build-args: |
            BASE_IMAGE=nvidia/cuda:12.1.0-runtime-ubuntu20.04
