name: Test JAX

on:
  # push:
  #   branches: [ "main" ] 
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '30 3 * * *'  # runs daily at 03:30 AM
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  jax-unit-tests:
    runs-on: [self-hosted, 1GPU]
    steps:
      - name: Print host information
        run: |
          hostname
          date
          nvcc --version
          nvidia-smi -L
          nvidia-smi

      - name: Print environment variables
        run: |
          env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          CONTAINER_REPOSITORY=`echo ${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          IMAGE_JAX="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}:jax"
          echo "IMAGE_JAX=${IMAGE_JAX}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run docker image
        run: |
          set -x
          docker run --runtime=nvidia --gpus all ${{ env.IMAGE_JAX }} test-jax.sh -b backend-independent
          docker run --runtime=nvidia --gpus all ${{ env.IMAGE_JAX }} test-jax.sh -b gpu