name: Build containers

on:
  push:
  schedule:
    - cron: '30 9 * * *'  # Pacific Time 01:30 AM in UTC
  workflow_dispatch:

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  jax:
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            workflow = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "jax-build.yaml",
              ref: context.ref,
              inputs: {
                NIGHTLY: ${{ github.event_name == 'schedule' }}
              },
            })

            console.log(workflow);


          
  # jax:
  #   uses: ./.github/workflows/jax-build.yaml
  #   with:
  #     NIGHTLY: ${{ github.event_name == 'schedule' }}
  #   secrets: inherit

  # t5x:
  #   uses: ./.github/workflows/t5x-build.yaml
  #   needs: jax
  #   with:
  #     NIGHTLY: ${{ github.event_name == 'schedule' }}
  #   secrets: inherit

