name: Nightly T5X build

on:
  workflow_run:
    workflows: [Nightly JAX build]
    types: [completed]
  workflow_dispatch:
    inputs:
      DEBUG:
        type: boolean
        description: Debug run, do not create nightly image
        default: true
        required: false

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  t5x:
    uses: ./.github/workflows/_build_t5x.yaml
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    with:
      NIGHTLY: ${{ github.event_name == 'workflow_run' || !inputs.DEBUG }}
    secrets: inherit

  on-upstream-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Upstream workflow failed, aborting run' && exit 1