name: Nightly JAX build

on:
  schedule:
    - cron: '30 9 * * *'  # Pacific Time 01:30 AM in UTC
  workflow_dispatch:
    inputs:
      AS_NIGHTLY:
        type: boolean
        description: Create nightly images?
        default: false
        required: false

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  jax:
    uses: ./.github/workflows/_build_jax.yaml
    with:
      NIGHTLY: ${{ github.event_name == 'schedule' || inputs.AS_NIGHTLY }}
    secrets: inherit