name: Build T5X container

on:
  # push:
  #   branches: [ "main" ] 
  # pull_request:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: '30 3 * * *'  # runs daily at 03:30 AM
  ## allow manual run from the Actions tab
  workflow_dispatch:
    inputs:
      BASE_IMAGE:
        description: 'a JAX image to serve as the base'
        required: true
        type: string

env:
  UPLD_IMAGE: ghcr.io/nvidia/t5x

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
        if: ${{github.ref != 'refs/head/main'}}

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.UPLD_IMAGE }}
          flavor: |
            latest=false
          tags: |
            type=sha

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          file: .github/container/Dockerfile.t5x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ inputs.BASE_IMAGE }}