name: Build T5X container

on:
  push:
  #   branches: [ "main" ] 
  pull_request:
  #   branches: [ "main" ]
  schedule:
    - cron: '30 3 * * *'  # runs daily at 03:30 AM
  ## allow manual run from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Print environment variables
        run: env

      - name: Set container tag
        run: |
          set -x
          CONTAINER_REGISTRY="ghcr.io"
          CONTAINER_REPOSITORY=`echo ${GITHUB_REPOSITORY} | tr [:upper:] [:lower:]`
          RUN_NUMBER=`printf "%08d" $GITHUB_RUN_NUMBER`
          DATE=`date +%Y-%m-%d`
          IMAGE_JAX="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}:jax"
          IMAGE_T5X="${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}:t5x"
          IMAGE_T5X_PIPELINE="${IMAGE_T5X}-${RUN_NUMBER}"
          IMAGE_T5X_DATED="${IMAGE_T5X}-${DATE}"
          echo "IMAGE_JAX=${IMAGE_JAX}" >> $GITHUB_ENV
          echo "IMAGE_T5X=${IMAGE_T5X}" >> $GITHUB_ENV
          echo "IMAGE_T5X_PIPELINE=${IMAGE_T5X_PIPELINE}" >> $GITHUB_ENV
          echo "IMAGE_T5X_DATED=${IMAGE_T5X_DATED}" >> $GITHUB_ENV

      - name: Check out the repository under ${GITHUB_WORKSPACE}
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker images
        uses: docker/build-push-action@v4
        with:
          context: .github/container
          push: true
          tags: ${{ env.IMAGE_T5X }},${{ env.IMAGE_T5X_PIPELINE }},${{ env.IMAGE_T5X_DATED }}
          file: .github/container/Dockerfile.t5x
          build-args: |
            BASE_IMAGE=${{ env.IMAGE_JAX }}