name: Weekly base container build

on:
  push:  # for debug only
  schedule:
    - cron: '30 13 * * 5'  # 5:30 AM every Friday

permissions:
  contents: read  # to fetch code
  actions:  write # to cancel previous workflows
  packages: write # to upload container

jobs:

  base:
    uses: ./.github/workflows/_build_base.yaml
    secrets: inherit